events {
    worker_connections 1024;
}

http {

    upstream park_backend {
        server park-app:8080;
    }

    server {
        listen 80;

        # Rutas API principal → park-app
        location /api/ {
            proxy_pass         http://park_backend;
            proxy_http_version 1.1;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   Authorization      $http_authorization;
            proxy_pass_header  Authorization;
        }

        # Health check
        location /health {
            proxy_pass http://park_backend/actuator/health;
        }

        # Fallback
        location / {
            return 404 '{"error":"Not found"}';
            add_header Content-Type application/json;
        }
    }
}
